
-- 01 Namesi 
insert into Districts (CityId,Name) values (1,'Aladað')
insert into Districts (CityId,Name) values (1,'Ceyhan')
insert into Districts (CityId,Name) values (1,'Çukurova')
insert into Districts (CityId,Name) values (1,'Feke')
insert into Districts (CityId,Name) values (1,'Ýmamoðlu')
insert into Districts (CityId,Name) values (1,'Karaisalý')
insert into Districts (CityId,Name) values (1,'Karataþ')
insert into Districts (CityId,Name) values (1,'Kozan')
insert into Districts (CityId,Name) values (1,'Pozantý')
insert into Districts (CityId,Name) values (1,'Saimbeyli')
insert into Districts (CityId,Name) values (1,'Sarýçam')
insert into Districts (CityId,Name) values (1,'Tufanbeyli')
insert into Districts (CityId,Name) values (1,'Yumurtalýk')
insert into Districts (CityId,Name) values (1,'Yüreðir')

-- 02 Namesi
insert into Districts (CityId,Name) values (2,'Besni')
insert into Districts (CityId,Name) values (2,'Çelikhan')
insert into Districts (CityId,Name) values (2,'Gerger')
insert into Districts (CityId,Name) values (2,'Gölbaþý')
insert into Districts (CityId,Name) values (2,'Kahta')
insert into Districts (CityId,Name) values (2,'Merkez')
insert into Districts (CityId,Name) values (2,'Samsat')
insert into Districts (CityId,Name) values (2,'Sincik')
insert into Districts (CityId,Name) values (2,'Tut')

-- 03 Namesi
insert into Districts (CityId,Name) values (3,'Baþmakçý')
insert into Districts (CityId,Name) values (3,'Bayat')
insert into Districts (CityId,Name) values (3,'Bolvadin')
insert into Districts (CityId,Name) values (3,'Çay')
insert into Districts (CityId,Name) values (3,'Çobanlar')
insert into Districts (CityId,Name) values (3,'Dazkýrý')
insert into Districts (CityId,Name) values (3,'Dinar')
insert into Districts (CityId,Name) values (3,'Emirdað')
insert into Districts (CityId,Name) values (3,'Evciler')
insert into Districts (CityId,Name) values (3,'Hocalar')
insert into Districts (CityId,Name) values (3,'Ýhsaniye')
insert into Districts (CityId,Name) values (3,'Ýscehisar')
insert into Districts (CityId,Name) values (3,'Kýzýlören')
insert into Districts (CityId,Name) values (3,'Merkez')
insert into Districts (CityId,Name) values (3,'Sandýklý')
insert into Districts (CityId,Name) values (3,'Sultandaðý')
insert into Districts (CityId,Name) values (3,'Þuhut')

-- 04 Namesi
insert into Districts (CityId,Name) values (4,'Diyadin')
insert into Districts (CityId,Name) values (4,'Doðubayazýt')
insert into Districts (CityId,Name) values (4,'Eleþkirt')
insert into Districts (CityId,Name) values (4,'Hamur')
insert into Districts (CityId,Name) values (4,'Merkez')
insert into Districts (CityId,Name) values (4,'Patnos')
insert into Districts (CityId,Name) values (4,'Taþlýçay')
insert into Districts (CityId,Name) values (4,'Tutak')

-- 05 Namesi
insert into Districts (CityId,Name) values (5,'Göynücek')
insert into Districts (CityId,Name) values (5,'Gümüþhacýköy')
insert into Districts (CityId,Name) values (5,'Hamamözü')
insert into Districts (CityId,Name) values (5,'Merkez')
insert into Districts (CityId,Name) values (5,'Merzifon')
insert into Districts (CityId,Name) values (5,'Suluova')
insert into Districts (CityId,Name) values (5,'Taþova')

-- 06 Namesi
insert into Districts (CityId,Name) values (6,'Akyurt')
insert into Districts (CityId,Name) values (6,'Altýndað')
insert into Districts (CityId,Name) values (6,'Ayaþ')
insert into Districts (CityId,Name) values (6,'Bala')
insert into Districts (CityId,Name) values (6,'Beypazarý')
insert into Districts (CityId,Name) values (6,'Çamlýdere')
insert into Districts (CityId,Name) values (6,'Çankaya')
insert into Districts (CityId,Name) values (6,'Çubuk')
insert into Districts (CityId,Name) values (6,'Elmadað')
insert into Districts (CityId,Name) values (6,'Etimesgut')
insert into Districts (CityId,Name) values (6,'Evren')
insert into Districts (CityId,Name) values (6,'Gölbaþý')
insert into Districts (CityId,Name) values (6,'Güdül')
insert into Districts (CityId,Name) values (6,'Haymana')
insert into Districts (CityId,Name) values (6,'Kalecik')
insert into Districts (CityId,Name) values (6,'Kazan')
insert into Districts (CityId,Name) values (6,'Keçiören')
insert into Districts (CityId,Name) values (6,'Kýzýlcahamam')
insert into Districts (CityId,Name) values (6,'Mamak')
insert into Districts (CityId,Name) values (6,'Nallýhan')
insert into Districts (CityId,Name) values (6,'Polatlý')
insert into Districts (CityId,Name) values (6,'Pursaklar')
insert into Districts (CityId,Name) values (6,'Sincan')
insert into Districts (CityId,Name) values (6,'Þereflikoçhisar')
insert into Districts (CityId,Name) values (6,'Yenimahalle')

-- 07 Namesi
insert into Districts (CityId,Name) values (7,'Akseki')
insert into Districts (CityId,Name) values (7,'Aksu')
insert into Districts (CityId,Name) values (7,'Alanya')
insert into Districts (CityId,Name) values (7,'Demre')
insert into Districts (CityId,Name) values (7,'Döþemealtý')
insert into Districts (CityId,Name) values (7,'Elmalý')
insert into Districts (CityId,Name) values (7,'Finike')
insert into Districts (CityId,Name) values (7,'Gazipaþa')
insert into Districts (CityId,Name) values (7,'Gündoðmuþ')
insert into Districts (CityId,Name) values (7,'Ýbradý')
insert into Districts (CityId,Name) values (7,'Kaþ')
insert into Districts (CityId,Name) values (7,'Kemer')
insert into Districts (CityId,Name) values (7,'Kepez')
insert into Districts (CityId,Name) values (7,'Konyaaltý')
insert into Districts (CityId,Name) values (7,'Korkuteli')
insert into Districts (CityId,Name) values (7,'Kumluca')
insert into Districts (CityId,Name) values (7,'Manavgat')
insert into Districts (CityId,Name) values (7,'Muratpaþa')
insert into Districts (CityId,Name) values (7,'Serik')
--- keremozer.com
-- 08 Ýlçesi 
insert into Districts (CityId,Name) values (8,'Ardanuç')
insert into Districts (CityId,Name) values (8,'Arhavi')
insert into Districts (CityId,Name) values (8,'Borçka')
insert into Districts (CityId,Name) values (8,'Hopa')
insert into Districts (CityId,Name) values (8,'Merkez')
insert into Districts (CityId,Name) values (8,'Murgul')
insert into Districts (CityId,Name) values (8,'Þavþat')
insert into Districts (CityId,Name) values (8,'Yusufeli')

-- 09 Ýlçesi 
insert into Districts (CityId,Name) values (9,'Bozdoðan')
insert into Districts (CityId,Name) values (9,'Buharkent')
insert into Districts (CityId,Name) values (9,'Çine')
insert into Districts (CityId,Name) values (9,'Didim')
insert into Districts (CityId,Name) values (9,'Efeler')
insert into Districts (CityId,Name) values (9,'Germencik')
insert into Districts (CityId,Name) values (9,'Ýncirliova')
insert into Districts (CityId,Name) values (9,'Karacasu')
insert into Districts (CityId,Name) values (9,'Karpuzlu')
insert into Districts (CityId,Name) values (9,'Koçarlý')
insert into Districts (CityId,Name) values (9,'Köþk')
insert into Districts (CityId,Name) values (9,'Kuþadasý')
insert into Districts (CityId,Name) values (9,'Kuyucak')
insert into Districts (CityId,Name) values (9,'Nazilli')
insert into Districts (CityId,Name) values (9,'Söke')
insert into Districts (CityId,Name) values (9,'Sultanhisar')
insert into Districts (CityId,Name) values (9,'Yenipazar')

-- 10 Ýlçesi 
insert into Districts (CityId,Name) values (10,'Altýeylül')
insert into Districts (CityId,Name) values (10,'Ayvalýk')
insert into Districts (CityId,Name) values (10,'Balya')
insert into Districts (CityId,Name) values (10,'Bandýrma')
insert into Districts (CityId,Name) values (10,'Bigadiç')
insert into Districts (CityId,Name) values (10,'Burhaniye')
insert into Districts (CityId,Name) values (10,'Dursunbey')
insert into Districts (CityId,Name) values (10,'Edremit')
insert into Districts (CityId,Name) values (10,'Erdek')
insert into Districts (CityId,Name) values (10,'Gömeç')
insert into Districts (CityId,Name) values (10,'Gönen')
insert into Districts (CityId,Name) values (10,'Havran')
insert into Districts (CityId,Name) values (10,'Ývrindi')
insert into Districts (CityId,Name) values (10,'Karesi')
insert into Districts (CityId,Name) values (10,'Kepsut')
insert into Districts (CityId,Name) values (10,'Manyas')
insert into Districts (CityId,Name) values (10,'Marmara')
insert into Districts (CityId,Name) values (10,'Savaþtepe')
insert into Districts (CityId,Name) values (10,'Sýndýrgý')
insert into Districts (CityId,Name) values (10,'Susurluk')

-- 11 Ýlçesi
insert into Districts (CityId,Name) values (11,'Bozüyük')
insert into Districts (CityId,Name) values (11,'Gölpazarý')
insert into Districts (CityId,Name) values (11,'Ýnhisar')
insert into Districts (CityId,Name) values (11,'Merkez')
insert into Districts (CityId,Name) values (11,'Osmaneli')
insert into Districts (CityId,Name) values (11,'Pazaryeri')
insert into Districts (CityId,Name) values (11,'Söðüt')
insert into Districts (CityId,Name) values (11,'Yenipazar')

-- 12 Ýlçesi
insert into Districts (CityId,Name) values (12,'Adaklý')
insert into Districts (CityId,Name) values (12,'Genç')
insert into Districts (CityId,Name) values (12,'Karlýova')
insert into Districts (CityId,Name) values (12,'Kiðý')
insert into Districts (CityId,Name) values (12,'Merkez')
insert into Districts (CityId,Name) values (12,'Solhan')
insert into Districts (CityId,Name) values (12,'Yayladere')
insert into Districts (CityId,Name) values (12,'Yedisu')

-- 13 Ýlçesi
insert into Districts (CityId,Name) values (13,'AdNamevaz')
insert into Districts (CityId,Name) values (13,'Ahlat')
insert into Districts (CityId,Name) values (13,'Güroymak')
insert into Districts (CityId,Name) values (13,'Hizan')
insert into Districts (CityId,Name) values (13,'Merkez')
insert into Districts (CityId,Name) values (13,'Mutki')
insert into Districts (CityId,Name) values (13,'Tatvan')

-- 14 Ýlçesi
insert into Districts (CityId,Name) values (14,'Dörtdivan')
insert into Districts (CityId,Name) values (14,'Gerede')
insert into Districts (CityId,Name) values (14,'Göynük')
insert into Districts (CityId,Name) values (14,'Kýbrýscýk')
insert into Districts (CityId,Name) values (14,'Mengen')
insert into Districts (CityId,Name) values (14,'Merkez')
insert into Districts (CityId,Name) values (14,'Mudurnu')
insert into Districts (CityId,Name) values (14,'Seben')
insert into Districts (CityId,Name) values (14,'Yeniçaða')

-- 15 Ýlçesi
insert into Districts (CityId,Name) values (15,'Aðlasun')
insert into Districts (CityId,Name) values (15,'Altýnyayla')
insert into Districts (CityId,Name) values (15,'Bucak')
insert into Districts (CityId,Name) values (15,'Çavdýr')
insert into Districts (CityId,Name) values (15,'Çeltikçi')
insert into Districts (CityId,Name) values (15,'Gölhisar')
insert into Districts (CityId,Name) values (15,'Karamanlý')
insert into Districts (CityId,Name) values (15,'Kemer')
insert into Districts (CityId,Name) values (15,'Merkez')
insert into Districts (CityId,Name) values (15,'Tefenni')
insert into Districts (CityId,Name) values (15,'Yeþilova')

-- 16 Ýlçesi
insert into Districts (CityId,Name) values (16,'Büyükorhan')
insert into Districts (CityId,Name) values (16,'Gemlik')
insert into Districts (CityId,Name) values (16,'Gürsu')
insert into Districts (CityId,Name) values (16,'Harmancýk')
insert into Districts (CityId,Name) values (16,'Ýnegöl')
insert into Districts (CityId,Name) values (16,'Ýznik')
insert into Districts (CityId,Name) values (16,'Karacabey')
insert into Districts (CityId,Name) values (16,'Keles')
insert into Districts (CityId,Name) values (16,'Kestel')
insert into Districts (CityId,Name) values (16,'Mudanya')
insert into Districts (CityId,Name) values (16,'Mustafa Kemal Paþa')
insert into Districts (CityId,Name) values (16,'Nilüfer')
insert into Districts (CityId,Name) values (16,'Orhaneli')
insert into Districts (CityId,Name) values (16,'Orhangazi')
insert into Districts (CityId,Name) values (16,'Osmangazi')
insert into Districts (CityId,Name) values (16,'Yeniþehir')
insert into Districts (CityId,Name) values (16,'Yýldýrým')

-- 17 Ýlçesi
insert into Districts (CityId,Name) values (17,'Ayvacýk')
insert into Districts (CityId,Name) values (17,'Bayramiç')
insert into Districts (CityId,Name) values (17,'Biga')
insert into Districts (CityId,Name) values (17,'Çan')
insert into Districts (CityId,Name) values (17,'Eceabat')
insert into Districts (CityId,Name) values (17,'Ezine')
insert into Districts (CityId,Name) values (17,'Gelibolu')
insert into Districts (CityId,Name) values (17,'Gökçeada')
insert into Districts (CityId,Name) values (17,'Lapseki')
insert into Districts (CityId,Name) values (17,'Merkez')
insert into Districts (CityId,Name) values (17,'Yenice')

-- 18 Ýlçesi
insert into Districts (CityId,Name) values (18,'Atkaracalar')
insert into Districts (CityId,Name) values (18,'Bayramören')
insert into Districts (CityId,Name) values (18,'Çerkeþ')
insert into Districts (CityId,Name) values (18,'Eldivan')
insert into Districts (CityId,Name) values (18,'Ilgaz')
insert into Districts (CityId,Name) values (18,'Kýzýlýrmak')
insert into Districts (CityId,Name) values (18,'Korgun')
insert into Districts (CityId,Name) values (18,'Kurþunlu')
insert into Districts (CityId,Name) values (18,'Merkez')
insert into Districts (CityId,Name) values (18,'Orta')
insert into Districts (CityId,Name) values (18,'Þabanözü')
insert into Districts (CityId,Name) values (18,'Yapraklý')
--- keremozer.com
-- 19 Ýlçesi
insert into Districts (CityId,Name) values (19,'Alaca')
insert into Districts (CityId,Name) values (19,'Bayat')
insert into Districts (CityId,Name) values (19,'Boðazkale')
insert into Districts (CityId,Name) values (19,'Dodurga')
insert into Districts (CityId,Name) values (19,'Ýskilip')
insert into Districts (CityId,Name) values (19,'Kargý')
insert into Districts (CityId,Name) values (19,'Laçin')
insert into Districts (CityId,Name) values (19,'Mecitözü')
insert into Districts (CityId,Name) values (19,'Merkez')
insert into Districts (CityId,Name) values (19,'Oðuzlar')
insert into Districts (CityId,Name) values (19,'Ortaköy')
insert into Districts (CityId,Name) values (19,'Osmancýk')
insert into Districts (CityId,Name) values (19,'Sungurlu')
insert into Districts (CityId,Name) values (19,'Uðurludað')

-- 20 Ýlçesi
insert into Districts (CityId,Name) values (20,'Acýpayam')
insert into Districts (CityId,Name) values (20,'Babadað')
insert into Districts (CityId,Name) values (20,'Baklan')
insert into Districts (CityId,Name) values (20,'Bekilli')
insert into Districts (CityId,Name) values (20,'Beyaðaç')
insert into Districts (CityId,Name) values (20,'Bozkurt')
insert into Districts (CityId,Name) values (20,'Buldan')
insert into Districts (CityId,Name) values (20,'Çal')
insert into Districts (CityId,Name) values (20,'Çameli')
insert into Districts (CityId,Name) values (20,'Çardak')
insert into Districts (CityId,Name) values (20,'Çivril')
insert into Districts (CityId,Name) values (20,'Güney')
insert into Districts (CityId,Name) values (20,'Honaz')
insert into Districts (CityId,Name) values (20,'Kale')
insert into Districts (CityId,Name) values (20,'Merkezefendi')
insert into Districts (CityId,Name) values (20,'Pamukkale')
insert into Districts (CityId,Name) values (20,'Sarayköy')
insert into Districts (CityId,Name) values (20,'Serinhisar')
insert into Districts (CityId,Name) values (20,'Tavas')

-- 21 Ýlçesi
insert into Districts (CityId,Name) values (21,'Baðlar')
insert into Districts (CityId,Name) values (21,'Bismil')
insert into Districts (CityId,Name) values (21,'Çermik')
insert into Districts (CityId,Name) values (21,'Çýnar')
insert into Districts (CityId,Name) values (21,'Çüngüþ')
insert into Districts (CityId,Name) values (21,'Dicle')
insert into Districts (CityId,Name) values (21,'Eðil')
insert into Districts (CityId,Name) values (21,'Ergani')
insert into Districts (CityId,Name) values (21,'Hani')
insert into Districts (CityId,Name) values (21,'Hazro')
insert into Districts (CityId,Name) values (21,'Kayapýnar')
insert into Districts (CityId,Name) values (21,'Kocaköy')
insert into Districts (CityId,Name) values (21,'Kulp')
insert into Districts (CityId,Name) values (21,'Lice')
insert into Districts (CityId,Name) values (21,'Silvan')
insert into Districts (CityId,Name) values (21,'Sur')
insert into Districts (CityId,Name) values (21,'Yeniþehir')

-- 22 Ýlçesi
insert into Districts (CityId,Name) values (22,'Enez')
insert into Districts (CityId,Name) values (22,'Havsa')
insert into Districts (CityId,Name) values (22,'Ýpsala')
insert into Districts (CityId,Name) values (22,'Keþan')
insert into Districts (CityId,Name) values (22,'Lalapaþa')
insert into Districts (CityId,Name) values (22,'Meriç')
insert into Districts (CityId,Name) values (22,'Merkez')
insert into Districts (CityId,Name) values (22,'Süloðlu')
insert into Districts (CityId,Name) values (22,'Uzunköprü')

-- 23 Ýlçesi
insert into Districts (CityId,Name) values (23,'Aðýn')
insert into Districts (CityId,Name) values (23,'Alacakaya')
insert into Districts (CityId,Name) values (23,'Arýcak')
insert into Districts (CityId,Name) values (23,'Baskil')
insert into Districts (CityId,Name) values (23,'Karakoçan')
insert into Districts (CityId,Name) values (23,'Keban')
insert into Districts (CityId,Name) values (23,'Kovancýlar')
insert into Districts (CityId,Name) values (23,'Maden')
insert into Districts (CityId,Name) values (23,'Merkez')
insert into Districts (CityId,Name) values (23,'Palu')
insert into Districts (CityId,Name) values (23,'Sivrice')


-- 24 Ýlçesi
insert into Districts (CityId,Name) values (24,'Çayýrlý')
insert into Districts (CityId,Name) values (24,'Ýliç')
insert into Districts (CityId,Name) values (24,'Kemah')
insert into Districts (CityId,Name) values (24,'Kemaliye')
insert into Districts (CityId,Name) values (24,'Merkez')
insert into Districts (CityId,Name) values (24,'Otlukbeli')
insert into Districts (CityId,Name) values (24,'Refahiye')
insert into Districts (CityId,Name) values (24,'Tercan')
insert into Districts (CityId,Name) values (24,'Üzümlü')

-- 25 Ýlçesi
insert into Districts (CityId,Name) values (25,'Aþkale')
insert into Districts (CityId,Name) values (25,'Aziziye')
insert into Districts (CityId,Name) values (25,'Çat')
insert into Districts (CityId,Name) values (25,'Hýnýs')
insert into Districts (CityId,Name) values (25,'Horasan')
insert into Districts (CityId,Name) values (25,'Ýspir')
insert into Districts (CityId,Name) values (25,'Karaçoban')
insert into Districts (CityId,Name) values (25,'Karayazý')
insert into Districts (CityId,Name) values (25,'Köprüköy')
insert into Districts (CityId,Name) values (25,'Narman')
insert into Districts (CityId,Name) values (25,'Oltu')
insert into Districts (CityId,Name) values (25,'Olur')
insert into Districts (CityId,Name) values (25,'Palandöken')
insert into Districts (CityId,Name) values (25,'Pasinler')
insert into Districts (CityId,Name) values (25,'Pazaryolu')
insert into Districts (CityId,Name) values (25,'Þenkaya')
insert into Districts (CityId,Name) values (25,'Tekman')
insert into Districts (CityId,Name) values (25,'Tortum')
insert into Districts (CityId,Name) values (25,'Uzundere')
insert into Districts (CityId,Name) values (25,'Yakutiye')

-- 26 Ýlçesi
insert into Districts (CityId,Name) values (26,'Alpu')
insert into Districts (CityId,Name) values (26,'Beylikova')
insert into Districts (CityId,Name) values (26,'Çifteler')
insert into Districts (CityId,Name) values (26,'Günyüzü')
insert into Districts (CityId,Name) values (26,'Han')
insert into Districts (CityId,Name) values (26,'Ýnönü')
insert into Districts (CityId,Name) values (26,'Mahmudiye')
insert into Districts (CityId,Name) values (26,'Mihalgazi')
insert into Districts (CityId,Name) values (26,'Mihalýççýk')
insert into Districts (CityId,Name) values (26,'Odunpazarý')
insert into Districts (CityId,Name) values (26,'Sarýcakaya')
insert into Districts (CityId,Name) values (26,'Seyitgazi')
insert into Districts (CityId,Name) values (26,'Sivrihisar')
insert into Districts (CityId,Name) values (26,'Tepebaþý')
--- keremozer.com
-- 27 Ýlçesi
insert into Districts (CityId,Name) values (27,'Araban')
insert into Districts (CityId,Name) values (27,'Ýslahiye')
insert into Districts (CityId,Name) values (27,'Karkamýþ')
insert into Districts (CityId,Name) values (27,'Nizip')
insert into Districts (CityId,Name) values (27,'Nurdaðý')
insert into Districts (CityId,Name) values (27,'Oðuzeli')
insert into Districts (CityId,Name) values (27,'Þahinbey')
insert into Districts (CityId,Name) values (27,'Þahinbey')
insert into Districts (CityId,Name) values (27,'Þehitkamil')
insert into Districts (CityId,Name) values (27,'Yavuzeli')

-- 28 Ýlçesi
insert into Districts (CityId,Name) values (28,'Alucra')
insert into Districts (CityId,Name) values (28,'Bulancak')
insert into Districts (CityId,Name) values (28,'Çamoluk')
insert into Districts (CityId,Name) values (28,'Çanakçý')
insert into Districts (CityId,Name) values (28,'Dereli')
insert into Districts (CityId,Name) values (28,'Doðankent')
insert into Districts (CityId,Name) values (28,'Espiye')
insert into Districts (CityId,Name) values (28,'Eynesil')
insert into Districts (CityId,Name) values (28,'Görele')
insert into Districts (CityId,Name) values (28,'Güce')
insert into Districts (CityId,Name) values (28,'Keþap')
insert into Districts (CityId,Name) values (28,'Merkez')
insert into Districts (CityId,Name) values (28,'Piraziz')
insert into Districts (CityId,Name) values (28,'Þebinkarahisar')
insert into Districts (CityId,Name) values (28,'Tirebolu')
insert into Districts (CityId,Name) values (28,'Yaðlýdere')

-- 29 Ýlçesi
insert into Districts (CityId,Name) values (29,'Kelkit')
insert into Districts (CityId,Name) values (29,'Köse')
insert into Districts (CityId,Name) values (29,'Kürtün')
insert into Districts (CityId,Name) values (29,'Merkez')
insert into Districts (CityId,Name) values (29,'Þiran')
insert into Districts (CityId,Name) values (29,'Torul')

-- 30 Ýlçesi
insert into Districts (CityId,Name) values (30,'Çukurca')
insert into Districts (CityId,Name) values (30,'Merkez')
insert into Districts (CityId,Name) values (30,'Þemdinli')
insert into Districts (CityId,Name) values (30,'Yüksekova')

-- 31 Ýlçesi
insert into Districts (CityId,Name) values (31,'Altýnözü')
insert into Districts (CityId,Name) values (31,'Antakya')
insert into Districts (CityId,Name) values (31,'Arsuz')
insert into Districts (CityId,Name) values (31,'Belen')
insert into Districts (CityId,Name) values (31,'Defne')
insert into Districts (CityId,Name) values (31,'Dörtyol')
insert into Districts (CityId,Name) values (31,'Erzin')
insert into Districts (CityId,Name) values (31,'Hassa')
insert into Districts (CityId,Name) values (31,'Ýskenderun')
insert into Districts (CityId,Name) values (31,'Kýrýkhan')
insert into Districts (CityId,Name) values (31,'Kumlu')
insert into Districts (CityId,Name) values (31,'Payas')
insert into Districts (CityId,Name) values (31,'Reyhanlý')
insert into Districts (CityId,Name) values (31,'Samandað')
insert into Districts (CityId,Name) values (31,'Yayladaðý')

-- 32 Ýlçesi
insert into Districts (CityId,Name) values (32,'Aksu')
insert into Districts (CityId,Name) values (32,'Atabey')
insert into Districts (CityId,Name) values (32,'Eðirdir')
insert into Districts (CityId,Name) values (32,'Gelendost')
insert into Districts (CityId,Name) values (32,'Gönen')
insert into Districts (CityId,Name) values (32,'Keçiborlu')
insert into Districts (CityId,Name) values (32,'Merkez')
insert into Districts (CityId,Name) values (32,'Senirkent')
insert into Districts (CityId,Name) values (32,'Sütçüler')
insert into Districts (CityId,Name) values (32,'Þarkikaraaðaç')
insert into Districts (CityId,Name) values (32,'Uluborlu')
insert into Districts (CityId,Name) values (32,'Yalvaç')
insert into Districts (CityId,Name) values (32,'Yeniþarbademli')
--- keremozer.com
-- 33 Ýlçesi
insert into Districts (CityId,Name) values (33,'Akdeniz')
insert into Districts (CityId,Name) values (33,'Anamur')
insert into Districts (CityId,Name) values (33,'Aydýncýk')
insert into Districts (CityId,Name) values (33,'Bozyazý')
insert into Districts (CityId,Name) values (33,'Çamlýyayla')
insert into Districts (CityId,Name) values (33,'Erdemli')
insert into Districts (CityId,Name) values (33,'Gülnar')
insert into Districts (CityId,Name) values (33,'Mezitli')
insert into Districts (CityId,Name) values (33,'Mut')
insert into Districts (CityId,Name) values (33,'Silifke')
insert into Districts (CityId,Name) values (33,'Tarsus')
insert into Districts (CityId,Name) values (33,'Tarsus')
insert into Districts (CityId,Name) values (33,'Yeniþehir')

-- 34 Ýlçesi
insert into Districts (CityId,Name) values (34,'Adalar')
insert into Districts (CityId,Name) values (34,'Arnavutköy')
insert into Districts (CityId,Name) values (34,'Ataþehir')
insert into Districts (CityId,Name) values (34,'Avcýlar')
insert into Districts (CityId,Name) values (34,'Baðcýlar')
insert into Districts (CityId,Name) values (34,'Bahçelievler')
insert into Districts (CityId,Name) values (34,'Bakýrköy')
insert into Districts (CityId,Name) values (34,'Baþakþehir')
insert into Districts (CityId,Name) values (34,'Bayrampaþa')
insert into Districts (CityId,Name) values (34,'Beþiktaþ')
insert into Districts (CityId,Name) values (34,'Beykoz')
insert into Districts (CityId,Name) values (34,'Beylikdüzü')
insert into Districts (CityId,Name) values (34,'Beyoðlu')
insert into Districts (CityId,Name) values (34,'Büyükçekmece')
insert into Districts (CityId,Name) values (34,'Çatalca')
insert into Districts (CityId,Name) values (34,'Çekmeköy')
insert into Districts (CityId,Name) values (34,'Esenler')
insert into Districts (CityId,Name) values (34,'Esenyurt')
insert into Districts (CityId,Name) values (34,'Eyüp')
insert into Districts (CityId,Name) values (34,'Fatih')
insert into Districts (CityId,Name) values (34,'Gaziosmanpaþa')
insert into Districts (CityId,Name) values (34,'Güngören')
insert into Districts (CityId,Name) values (34,'Kadýköy')
insert into Districts (CityId,Name) values (34,'Kaðýthane')
insert into Districts (CityId,Name) values (34,'Kartal')
insert into Districts (CityId,Name) values (34,'Küçükçekmece')
insert into Districts (CityId,Name) values (34,'Maltepe')
insert into Districts (CityId,Name) values (34,'Pendik')
insert into Districts (CityId,Name) values (34,'Sancaktepe')
insert into Districts (CityId,Name) values (34,'Sarýyer')
insert into Districts (CityId,Name) values (34,'Silivri')
insert into Districts (CityId,Name) values (34,'Sultanbeyli')
insert into Districts (CityId,Name) values (34,'Sultangazi')
insert into Districts (CityId,Name) values (34,'Þile')
insert into Districts (CityId,Name) values (34,'Þiþli')
insert into Districts (CityId,Name) values (34,'Tuzla')
insert into Districts (CityId,Name) values (34,'Ümraniye')
insert into Districts (CityId,Name) values (34,'Üsküdar')
insert into Districts (CityId,Name) values (34,'Zeytinburnu')

-- 35 Ýlçesi
insert into Districts (CityId,Name) values (35,'Aliaða')
insert into Districts (CityId,Name) values (35,'Balçova')
insert into Districts (CityId,Name) values (35,'Bayýndýr')
insert into Districts (CityId,Name) values (35,'Bayraklý')
insert into Districts (CityId,Name) values (35,'Bergama')
insert into Districts (CityId,Name) values (35,'Beydað')
insert into Districts (CityId,Name) values (35,'Bornova')
insert into Districts (CityId,Name) values (35,'Buca')
insert into Districts (CityId,Name) values (35,'Çeþme')
insert into Districts (CityId,Name) values (35,'Çiðli')
insert into Districts (CityId,Name) values (35,'Dikili')
insert into Districts (CityId,Name) values (35,'Foça')
insert into Districts (CityId,Name) values (35,'Gaziemir')
insert into Districts (CityId,Name) values (35,'Güzelbahçe')
insert into Districts (CityId,Name) values (35,'Karabaðlar')
insert into Districts (CityId,Name) values (35,'Karaburun')
insert into Districts (CityId,Name) values (35,'Karþýyaka')
insert into Districts (CityId,Name) values (35,'Kemalpaþa')
insert into Districts (CityId,Name) values (35,'Kýnýk')
insert into Districts (CityId,Name) values (35,'Kiraz')
insert into Districts (CityId,Name) values (35,'Konak')
insert into Districts (CityId,Name) values (35,'Menderes')
insert into Districts (CityId,Name) values (35,'Menemen')
insert into Districts (CityId,Name) values (35,'Narlýdere')
insert into Districts (CityId,Name) values (35,'Ödemiþ')
insert into Districts (CityId,Name) values (35,'Seferihisar')
insert into Districts (CityId,Name) values (35,'Selçuk')
insert into Districts (CityId,Name) values (35,'Tire')
insert into Districts (CityId,Name) values (35,'Torbalý')
insert into Districts (CityId,Name) values (35,'Urla')

-- 36 Ýlçesi
insert into Districts (CityId,Name) values (36,'Akyaka')
insert into Districts (CityId,Name) values (36,'Arpaçay')
insert into Districts (CityId,Name) values (36,'Digor')
insert into Districts (CityId,Name) values (36,'Kaðýzman')
insert into Districts (CityId,Name) values (36,'Merkez')
insert into Districts (CityId,Name) values (36,'Sarýkamýþ')
insert into Districts (CityId,Name) values (36,'Selim')
insert into Districts (CityId,Name) values (36,'Susuz')

-- 37 Ýlçesi
insert into Districts (CityId,Name) values (37,'Abana')
insert into Districts (CityId,Name) values (37,'Aðlý')
insert into Districts (CityId,Name) values (37,'Araç')
insert into Districts (CityId,Name) values (37,'Azdavay')
insert into Districts (CityId,Name) values (37,'Bozkurt')
insert into Districts (CityId,Name) values (37,'Cide')
insert into Districts (CityId,Name) values (37,'Çatalzeytin')
insert into Districts (CityId,Name) values (37,'Daday')
insert into Districts (CityId,Name) values (37,'Devrekani')
insert into Districts (CityId,Name) values (37,'Doðanyurt')
insert into Districts (CityId,Name) values (37,'Hanönü')
insert into Districts (CityId,Name) values (37,'Ýhsangazi')
insert into Districts (CityId,Name) values (37,'Ýnebolu')
insert into Districts (CityId,Name) values (37,'Küre')
insert into Districts (CityId,Name) values (37,'Merkez')
insert into Districts (CityId,Name) values (37,'Pýnarbaþý')
insert into Districts (CityId,Name) values (37,'Seydiler')
insert into Districts (CityId,Name) values (37,'Þenpazar')
insert into Districts (CityId,Name) values (37,'Taþköprü')
insert into Districts (CityId,Name) values (37,'Tosya')

-- 38 Ýlçesi
insert into Districts (CityId,Name) values (38,'Akkýþla')
insert into Districts (CityId,Name) values (38,'Bünyan')
insert into Districts (CityId,Name) values (38,'Develi')
insert into Districts (CityId,Name) values (38,'Felahiye')
insert into Districts (CityId,Name) values (38,'Hacýlar')
insert into Districts (CityId,Name) values (38,'Ýncesu')
insert into Districts (CityId,Name) values (38,'Kocasinan')
insert into Districts (CityId,Name) values (38,'Melikgazi')
insert into Districts (CityId,Name) values (38,'Özvatan')
insert into Districts (CityId,Name) values (38,'Pýnarbaþý')
insert into Districts (CityId,Name) values (38,'Sarýoðlan')
insert into Districts (CityId,Name) values (38,'Sarýz')
insert into Districts (CityId,Name) values (38,'Talas')
insert into Districts (CityId,Name) values (38,'Tomarza')
insert into Districts (CityId,Name) values (38,'Yahyalý')
insert into Districts (CityId,Name) values (38,'Yeþilhisar')

-- 39 Ýlçesi
insert into Districts (CityId,Name) values (39,'Babaeski')
insert into Districts (CityId,Name) values (39,'Demirköy')
insert into Districts (CityId,Name) values (39,'Kofçaz')
insert into Districts (CityId,Name) values (39,'Lüleburgaz')
insert into Districts (CityId,Name) values (39,'Merkez')
insert into Districts (CityId,Name) values (39,'Pehlivanköy')
insert into Districts (CityId,Name) values (39,'Pýnarhisar')
insert into Districts (CityId,Name) values (39,'Vize')

-- 40 Ýlçesi
insert into Districts (CityId,Name) values (40,'Akçakent')
insert into Districts (CityId,Name) values (40,'Akpýnar')
insert into Districts (CityId,Name) values (40,'Boztepe')
insert into Districts (CityId,Name) values (40,'Çiçekdaðý')
insert into Districts (CityId,Name) values (40,'Kaman')
insert into Districts (CityId,Name) values (40,'Merkez')
insert into Districts (CityId,Name) values (40,'Mucur')

-- 41 Ýlçesi
insert into Districts (CityId,Name) values (41,'Baþiskele')
insert into Districts (CityId,Name) values (41,'Çayýrova')
insert into Districts (CityId,Name) values (41,'Darýca')
insert into Districts (CityId,Name) values (41,'Derince')
insert into Districts (CityId,Name) values (41,'Dilovasý')
insert into Districts (CityId,Name) values (41,'Gebze')
insert into Districts (CityId,Name) values (41,'Gölcük')
insert into Districts (CityId,Name) values (41,'Ýzmit')
insert into Districts (CityId,Name) values (41,'Kandýra')
insert into Districts (CityId,Name) values (41,'Karamürsel')
insert into Districts (CityId,Name) values (41,'Kartepe')
insert into Districts (CityId,Name) values (41,'Körfez')

-- 42 Ýlçesi
insert into Districts (CityId,Name) values (42,'Ahýrlý')
insert into Districts (CityId,Name) values (42,'Akören')
insert into Districts (CityId,Name) values (42,'Akþehir')
insert into Districts (CityId,Name) values (42,'Altýnekin')
insert into Districts (CityId,Name) values (42,'Beyþehir')
insert into Districts (CityId,Name) values (42,'Bozkýr')
insert into Districts (CityId,Name) values (42,'Cihanbeyli')
insert into Districts (CityId,Name) values (42,'Çeltik')
insert into Districts (CityId,Name) values (42,'Çumra')
insert into Districts (CityId,Name) values (42,'Derbent')
insert into Districts (CityId,Name) values (42,'Derebucak')
insert into Districts (CityId,Name) values (42,'Doðanhisar')
insert into Districts (CityId,Name) values (42,'Emirgazi')
insert into Districts (CityId,Name) values (42,'Ereðli')
insert into Districts (CityId,Name) values (42,'Güneysýnýr')
insert into Districts (CityId,Name) values (42,'Hadim')
insert into Districts (CityId,Name) values (42,'Halkapýnar')
insert into Districts (CityId,Name) values (42,'Hüyük')
insert into Districts (CityId,Name) values (42,'Ilgýn')
insert into Districts (CityId,Name) values (42,'Kadýnhaný')
insert into Districts (CityId,Name) values (42,'Karapýnar')
insert into Districts (CityId,Name) values (42,'Karatay')
insert into Districts (CityId,Name) values (42,'Kulu')
insert into Districts (CityId,Name) values (42,'Meram')
insert into Districts (CityId,Name) values (42,'Sarayönü')
insert into Districts (CityId,Name) values (42,'Selçuklu')
insert into Districts (CityId,Name) values (42,'Seydiþehir')
insert into Districts (CityId,Name) values (42,'Taþkent')
insert into Districts (CityId,Name) values (42,'Tuzlukçu')
insert into Districts (CityId,Name) values (42,'Yalýhüyük')
insert into Districts (CityId,Name) values (42,'Yunak')

-- 43 Ýlçesi
insert into Districts (CityId,Name) values (43,'Altýntaþ')
insert into Districts (CityId,Name) values (43,'Aslanapa')
insert into Districts (CityId,Name) values (43,'Çavdarhisar')
insert into Districts (CityId,Name) values (43,'Domaniç')
insert into Districts (CityId,Name) values (43,'Dumlupýnar')
insert into Districts (CityId,Name) values (43,'Emet')
insert into Districts (CityId,Name) values (43,'Gediz')
insert into Districts (CityId,Name) values (43,'Hisarcýk')
insert into Districts (CityId,Name) values (43,'Merkez')
insert into Districts (CityId,Name) values (43,'Pazarlar')
insert into Districts (CityId,Name) values (43,'Simav')
insert into Districts (CityId,Name) values (43,'Þaphane')
insert into Districts (CityId,Name) values (43,'Tavþanlý')
--- keremozer.com
-- 44 Ýlçesi
insert into Districts (CityId,Name) values (44,'Akçadað')
insert into Districts (CityId,Name) values (44,'Arapgir')
insert into Districts (CityId,Name) values (44,'Arguvan')
insert into Districts (CityId,Name) values (44,'Battalgazi')
insert into Districts (CityId,Name) values (44,'Darende')
insert into Districts (CityId,Name) values (44,'Doðanþehir')
insert into Districts (CityId,Name) values (44,'Doðanyol')
insert into Districts (CityId,Name) values (44,'Hekimhan')
insert into Districts (CityId,Name) values (44,'Kale')
insert into Districts (CityId,Name) values (44,'Kuluncak')
insert into Districts (CityId,Name) values (44,'Pütürge')
insert into Districts (CityId,Name) values (44,'Yazýhan')
insert into Districts (CityId,Name) values (44,'Yeþilyurt')

-- 45 Ýlçesi
insert into Districts (CityId,Name) values (45,'Ahmetli')
insert into Districts (CityId,Name) values (45,'Akhisar')
insert into Districts (CityId,Name) values (45,'Alaþehir')
insert into Districts (CityId,Name) values (45,'Demirci')
insert into Districts (CityId,Name) values (45,'Gölmarmara')
insert into Districts (CityId,Name) values (45,'Gördes')
insert into Districts (CityId,Name) values (45,'Kýrkaðaç')
insert into Districts (CityId,Name) values (45,'Köprübaþý')
insert into Districts (CityId,Name) values (45,'Kula')
insert into Districts (CityId,Name) values (45,'Salihli')
insert into Districts (CityId,Name) values (45,'Sarýgöl')
insert into Districts (CityId,Name) values (45,'Saruhanlý')
insert into Districts (CityId,Name) values (45,'Selendi')
insert into Districts (CityId,Name) values (45,'Soma')
insert into Districts (CityId,Name) values (45,'Þehzadeler')
insert into Districts (CityId,Name) values (45,'Turgutlu')
insert into Districts (CityId,Name) values (45,'Yunusemre')

-- 46 Ýlçesi
insert into Districts (CityId,Name) values (46,'Afþin')
insert into Districts (CityId,Name) values (46,'Andýrýn')
insert into Districts (CityId,Name) values (46,'Çaðlayancerit')
insert into Districts (CityId,Name) values (46,'Dulkadiroðlu')
insert into Districts (CityId,Name) values (46,'Ekinözü')
insert into Districts (CityId,Name) values (46,'Elbistan')
insert into Districts (CityId,Name) values (46,'Göksun')
insert into Districts (CityId,Name) values (46,'Nurhak')
insert into Districts (CityId,Name) values (46,'Onikiþubat')
insert into Districts (CityId,Name) values (46,'Pazarcýk')
insert into Districts (CityId,Name) values (46,'Türkoðlu')
--- keremozer.com
-- 47 Ýlçesi
insert into Districts (CityId,Name) values (47,'Artuklu')
insert into Districts (CityId,Name) values (47,'Dargeçit')
insert into Districts (CityId,Name) values (47,'Derik')
insert into Districts (CityId,Name) values (47,'Kýzýltepe')
insert into Districts (CityId,Name) values (47,'Mazýdaðý')
insert into Districts (CityId,Name) values (47,'Midyat')
insert into Districts (CityId,Name) values (47,'Nusaybin')
insert into Districts (CityId,Name) values (47,'Ömerli')
insert into Districts (CityId,Name) values (47,'Savur')
insert into Districts (CityId,Name) values (47,'Yeþilli')

-- 48 Ýlçesi
insert into Districts (CityId,Name) values (48,'Bodrum')
insert into Districts (CityId,Name) values (48,'Dalaman')
insert into Districts (CityId,Name) values (48,'Datça')
insert into Districts (CityId,Name) values (48,'Fethiye')
insert into Districts (CityId,Name) values (48,'Kavaklýdere')
insert into Districts (CityId,Name) values (48,'Köyceðiz')
insert into Districts (CityId,Name) values (48,'Marmaris')
insert into Districts (CityId,Name) values (48,'Menteþe')
insert into Districts (CityId,Name) values (48,'Milas')
insert into Districts (CityId,Name) values (48,'Ortaca')
insert into Districts (CityId,Name) values (48,'Seydikemer')
insert into Districts (CityId,Name) values (48,'Ula')
insert into Districts (CityId,Name) values (48,'Yataðan')

-- 49 Ýlçesi
insert into Districts (CityId,Name) values (49,'Bulanýk')
insert into Districts (CityId,Name) values (49,'Hasköy')
insert into Districts (CityId,Name) values (49,'Korkut')
insert into Districts (CityId,Name) values (49,'Malazgirt')
insert into Districts (CityId,Name) values (49,'Merkez')
insert into Districts (CityId,Name) values (49,'Varto')

-- 50 Ýlçesi
insert into Districts (CityId,Name) values (50,'Acýgöl')
insert into Districts (CityId,Name) values (50,'Avanos')
insert into Districts (CityId,Name) values (50,'Derinkuyu')
insert into Districts (CityId,Name) values (50,'Gülþehir')
insert into Districts (CityId,Name) values (50,'Hacýbektaþ')
insert into Districts (CityId,Name) values (50,'Kozaklý')
insert into Districts (CityId,Name) values (50,'Merkez')
insert into Districts (CityId,Name) values (50,'Ürgüp')

-- 51 Ýlçesi
insert into Districts (CityId,Name) values (51,'Altunhisar')
insert into Districts (CityId,Name) values (51,'Bor')
insert into Districts (CityId,Name) values (51,'Çamardý')
insert into Districts (CityId,Name) values (51,'Çiftlik')
insert into Districts (CityId,Name) values (51,'Merkez')
insert into Districts (CityId,Name) values (51,'Ulukýþla')
--- keremozer.com
-- 52 Ýlçesi
insert into Districts (CityId,Name) values (52,'Akkuþ')
insert into Districts (CityId,Name) values (52,'Altýnordu')
insert into Districts (CityId,Name) values (52,'Aybastý')
insert into Districts (CityId,Name) values (52,'Çamaþ')
insert into Districts (CityId,Name) values (52,'Çatalpýnar')
insert into Districts (CityId,Name) values (52,'Çaybaþý')
insert into Districts (CityId,Name) values (52,'Fatsa')
insert into Districts (CityId,Name) values (52,'Gölköy')
insert into Districts (CityId,Name) values (52,'Gülyalý')
insert into Districts (CityId,Name) values (52,'Gürgentepe')
insert into Districts (CityId,Name) values (52,'Ýkizce')
insert into Districts (CityId,Name) values (52,'Kabadüz')
insert into Districts (CityId,Name) values (52,'Kabataþ')
insert into Districts (CityId,Name) values (52,'Korgan')
insert into Districts (CityId,Name) values (52,'Kumru')
insert into Districts (CityId,Name) values (52,'Mesudiye')
insert into Districts (CityId,Name) values (52,'Perþembe')
insert into Districts (CityId,Name) values (52,'Ulubey')
insert into Districts (CityId,Name) values (52,'Ünye')

-- 53 Ýlçesi
insert into Districts (CityId,Name) values (53,'Ardeþen')
insert into Districts (CityId,Name) values (53,'Çamlýhemþin')
insert into Districts (CityId,Name) values (53,'Çayeli')
insert into Districts (CityId,Name) values (53,'Derepazarý')
insert into Districts (CityId,Name) values (53,'Fýndýklý')
insert into Districts (CityId,Name) values (53,'Güneysu')
insert into Districts (CityId,Name) values (53,'Hemþin')
insert into Districts (CityId,Name) values (53,'Ýkizdere')
insert into Districts (CityId,Name) values (53,'Ýyidere')
insert into Districts (CityId,Name) values (53,'Kalkandere')
insert into Districts (CityId,Name) values (53,'Merkez')
insert into Districts (CityId,Name) values (53,'Pazar')
--- keremozer.com
-- 54 Ýlçesi
insert into Districts (CityId,Name) values (54,'Adapazarý')
insert into Districts (CityId,Name) values (54,'Akyazý')
insert into Districts (CityId,Name) values (54,'Arifiye')
insert into Districts (CityId,Name) values (54,'Erenler')
insert into Districts (CityId,Name) values (54,'Ferizli')
insert into Districts (CityId,Name) values (54,'Geyve')
insert into Districts (CityId,Name) values (54,'Hendek')
insert into Districts (CityId,Name) values (54,'Karapürçek')
insert into Districts (CityId,Name) values (54,'Karasu')
insert into Districts (CityId,Name) values (54,'Kaynarca')
insert into Districts (CityId,Name) values (54,'Kocaali')
insert into Districts (CityId,Name) values (54,'Pamukova')
insert into Districts (CityId,Name) values (54,'Sapanca')
insert into Districts (CityId,Name) values (54,'Serdivan')
insert into Districts (CityId,Name) values (54,'Söðütlü')
insert into Districts (CityId,Name) values (54,'Taraklý')

-- 55 Ýlçesi
insert into Districts (CityId,Name) values (55,'19 Mayýs')
insert into Districts (CityId,Name) values (55,'Alaçam')
insert into Districts (CityId,Name) values (55,'Asarcýk')
insert into Districts (CityId,Name) values (55,'Atakum')
insert into Districts (CityId,Name) values (55,'Ayvacýk')
insert into Districts (CityId,Name) values (55,'Bafra')
insert into Districts (CityId,Name) values (55,'Canik')
insert into Districts (CityId,Name) values (55,'Çarþamba')
insert into Districts (CityId,Name) values (55,'Havza')
insert into Districts (CityId,Name) values (55,'Ýlkadým')
insert into Districts (CityId,Name) values (55,'Kavak')
insert into Districts (CityId,Name) values (55,'Ladik')
insert into Districts (CityId,Name) values (55,'Salýpazarý')
insert into Districts (CityId,Name) values (55,'Tekkeköy')
insert into Districts (CityId,Name) values (55,'Terme')
insert into Districts (CityId,Name) values (55,'Vezirköprü')
insert into Districts (CityId,Name) values (55,'Yakakent')

-- 56 Ýlçesi
insert into Districts (CityId,Name) values (56,'Baykan')
insert into Districts (CityId,Name) values (56,'Eruh')
insert into Districts (CityId,Name) values (56,'Kurtalan')
insert into Districts (CityId,Name) values (56,'Merkez')
insert into Districts (CityId,Name) values (56,'Pervari')
insert into Districts (CityId,Name) values (56,'Þirvan')
insert into Districts (CityId,Name) values (56,'Tillo')

-- 57 Ýlçesi
insert into Districts (CityId,Name) values (57,'Ayancýk')
insert into Districts (CityId,Name) values (57,'Boyabat')
insert into Districts (CityId,Name) values (57,'Dikmen')
insert into Districts (CityId,Name) values (57,'Duraðan')
insert into Districts (CityId,Name) values (57,'Erfelek')
insert into Districts (CityId,Name) values (57,'Gerze')
insert into Districts (CityId,Name) values (57,'Merkez')
insert into Districts (CityId,Name) values (57,'Saraydüzü')
insert into Districts (CityId,Name) values (57,'Türkeli')

-- 58 Ýlçesi
insert into Districts (CityId,Name) values (58,'Akýncýlar')
insert into Districts (CityId,Name) values (58,'Altýnyayla')
insert into Districts (CityId,Name) values (58,'Divriði')
insert into Districts (CityId,Name) values (58,'Doðanþar')
insert into Districts (CityId,Name) values (58,'Gemerek')
insert into Districts (CityId,Name) values (58,'Gölova')
insert into Districts (CityId,Name) values (58,'Gürün')
insert into Districts (CityId,Name) values (58,'Hafik')
insert into Districts (CityId,Name) values (58,'Ýmranlý')
insert into Districts (CityId,Name) values (58,'Kangal')
insert into Districts (CityId,Name) values (58,'Koyulhisar')
insert into Districts (CityId,Name) values (58,'Merkez')
insert into Districts (CityId,Name) values (58,'Suþehri')
insert into Districts (CityId,Name) values (58,'Þarkýþla')
insert into Districts (CityId,Name) values (58,'Ulaþ')
insert into Districts (CityId,Name) values (58,'Yýldýzeli')
insert into Districts (CityId,Name) values (58,'Zara')

-- 59 Ýlçesi
insert into Districts (CityId,Name) values (59,'Çerkezköy')
insert into Districts (CityId,Name) values (59,'Çorlu')
insert into Districts (CityId,Name) values (59,'Ergene')
insert into Districts (CityId,Name) values (59,'Hayrabolu')
insert into Districts (CityId,Name) values (59,'Malkara')
insert into Districts (CityId,Name) values (59,'Marmaraereðlisi')
insert into Districts (CityId,Name) values (59,'Muratlý')
insert into Districts (CityId,Name) values (59,'Saray')
insert into Districts (CityId,Name) values (59,'Süleymanpaþa')
insert into Districts (CityId,Name) values (59,'Þarköy')
--- keremozer.com
-- 60 Ýlçesi
insert into Districts (CityId,Name) values (60,'Almus')
insert into Districts (CityId,Name) values (60,'Artova')
insert into Districts (CityId,Name) values (60,'Baþçiftlik')
insert into Districts (CityId,Name) values (60,'Erbaa')
insert into Districts (CityId,Name) values (60,'Merkez')
insert into Districts (CityId,Name) values (60,'Niksar')
insert into Districts (CityId,Name) values (60,'Pazar')
insert into Districts (CityId,Name) values (60,'Reþadiye')
insert into Districts (CityId,Name) values (60,'Sulusaray')
insert into Districts (CityId,Name) values (60,'Turhal')
insert into Districts (CityId,Name) values (60,'Yeþilyurt')
insert into Districts (CityId,Name) values (60,'Zile')

-- 61 Ýlçesi
insert into Districts (CityId,Name) values (61,'Akçaabat')
insert into Districts (CityId,Name) values (61,'Araklý')
insert into Districts (CityId,Name) values (61,'Arsin')
insert into Districts (CityId,Name) values (61,'Beþikdüzü')
insert into Districts (CityId,Name) values (61,'Çarþýbaþý')
insert into Districts (CityId,Name) values (61,'Çaykara')
insert into Districts (CityId,Name) values (61,'Dernekpazarý')
insert into Districts (CityId,Name) values (61,'Düzköy')
insert into Districts (CityId,Name) values (61,'Hayrat')
insert into Districts (CityId,Name) values (61,'Köprübaþý')
insert into Districts (CityId,Name) values (61,'Maçka')
insert into Districts (CityId,Name) values (61,'Of')
insert into Districts (CityId,Name) values (61,'Ortahisar')
insert into Districts (CityId,Name) values (61,'Sürmene')
insert into Districts (CityId,Name) values (61,'Þalpazarý')
insert into Districts (CityId,Name) values (61,'Tonya')
insert into Districts (CityId,Name) values (61,'Vakfýkebir')
insert into Districts (CityId,Name) values (61,'Yomra')

-- 62 Ýlçesi
insert into Districts (CityId,Name) values (62,'Çemiþgezek')
insert into Districts (CityId,Name) values (62,'Hozat')
insert into Districts (CityId,Name) values (62,'Mazgirt')
insert into Districts (CityId,Name) values (62,'Merkez')
insert into Districts (CityId,Name) values (62,'Nazýmiye')
insert into Districts (CityId,Name) values (62,'Ovacýk')
insert into Districts (CityId,Name) values (62,'Pertek')
insert into Districts (CityId,Name) values (62,'Pülümür')

-- 63 Ýlçesi
insert into Districts (CityId,Name) values (63,'Akçakale')
insert into Districts (CityId,Name) values (63,'Birecik')
insert into Districts (CityId,Name) values (63,'Bozova')
insert into Districts (CityId,Name) values (63,'Ceylanpýnar')
insert into Districts (CityId,Name) values (63,'Eyyübiye')
insert into Districts (CityId,Name) values (63,'Halfeti')
insert into Districts (CityId,Name) values (63,'Haliliye')
insert into Districts (CityId,Name) values (63,'Harran')
insert into Districts (CityId,Name) values (63,'Hilvan')
insert into Districts (CityId,Name) values (63,'Karaköprü')
insert into Districts (CityId,Name) values (63,'Siverek')
insert into Districts (CityId,Name) values (63,'Suruç')
insert into Districts (CityId,Name) values (63,'Viranþehir')
--- keremozer.com
-- 64 Ýlçesi
insert into Districts (CityId,Name) values (64,'Banaz')
insert into Districts (CityId,Name) values (64,'Eþme')
insert into Districts (CityId,Name) values (64,'Karahallý')
insert into Districts (CityId,Name) values (64,'Merkez')
insert into Districts (CityId,Name) values (64,'Sivaslý')
insert into Districts (CityId,Name) values (64,'Ulubey')

-- 65 Ýlçesi
insert into Districts (CityId,Name) values (65,'Bahçesaray')
insert into Districts (CityId,Name) values (65,'Baþkale')
insert into Districts (CityId,Name) values (65,'Çaldýran')
insert into Districts (CityId,Name) values (65,'Çatak')
insert into Districts (CityId,Name) values (65,'Edremit')
insert into Districts (CityId,Name) values (65,'Erciþ')
insert into Districts (CityId,Name) values (65,'Gevaþ')
insert into Districts (CityId,Name) values (65,'Gürpýnar')
insert into Districts (CityId,Name) values (65,'Ýpekyolu')
insert into Districts (CityId,Name) values (65,'Muradiye')
insert into Districts (CityId,Name) values (65,'Özalp')
insert into Districts (CityId,Name) values (65,'Saray')
insert into Districts (CityId,Name) values (65,'Tuþba')

-- 66 Ýlçesi
insert into Districts (CityId,Name) values (66,'Akdaðmadeni')
insert into Districts (CityId,Name) values (66,'Aydýncýk')
insert into Districts (CityId,Name) values (66,'Boðazlýyan')
insert into Districts (CityId,Name) values (66,'Çandýr')
insert into Districts (CityId,Name) values (66,'Çayýralan')
insert into Districts (CityId,Name) values (66,'Çekerek')
insert into Districts (CityId,Name) values (66,'Kadýþehri')
insert into Districts (CityId,Name) values (66,'Merkez')
insert into Districts (CityId,Name) values (66,'Saraykent')
insert into Districts (CityId,Name) values (66,'Sarýkaya')
insert into Districts (CityId,Name) values (66,'Sorgun')
insert into Districts (CityId,Name) values (66,'Þefaatli')
insert into Districts (CityId,Name) values (66,'Yenifakýlý')
insert into Districts (CityId,Name) values (66,'Yerköy')

-- 67 Ýlçesi
insert into Districts (CityId,Name) values (67,'Alaplý')
insert into Districts (CityId,Name) values (67,'Çaycuma')
insert into Districts (CityId,Name) values (67,'Devrek')
insert into Districts (CityId,Name) values (67,'Ereðli')
insert into Districts (CityId,Name) values (67,'Gökçebey')
insert into Districts (CityId,Name) values (67,'Merkez')

-- 68 Ýlçesi
insert into Districts (CityId,Name) values (68,'Aðaçören')
insert into Districts (CityId,Name) values (68,'Eskil')
insert into Districts (CityId,Name) values (68,'Gülaðaç')
insert into Districts (CityId,Name) values (68,'Güzelyurt')
insert into Districts (CityId,Name) values (68,'Merkez')
insert into Districts (CityId,Name) values (68,'Ortaköy')
insert into Districts (CityId,Name) values (68,'Sarýyahþi')

-- 69 Ýlçesi
insert into Districts (CityId,Name) values (69,'Aydýntepe')
insert into Districts (CityId,Name) values (69,'Demirözü')
insert into Districts (CityId,Name) values (69,'Merkez')

-- 70 Ýlçesi
insert into Districts (CityId,Name) values (70,'Ayrancý')
insert into Districts (CityId,Name) values (70,'Baþyayla')
insert into Districts (CityId,Name) values (70,'Ermenek')
insert into Districts (CityId,Name) values (70,'Kazýmkarabekir')
insert into Districts (CityId,Name) values (70,'Merkez')
insert into Districts (CityId,Name) values (70,'Sarýveliler')
--- keremozer.com
-- 71 Ýlçesi
insert into Districts (CityId,Name) values (71,'Bahþili')
insert into Districts (CityId,Name) values (71,'Balýþeyh')
insert into Districts (CityId,Name) values (71,'Çelebi')
insert into Districts (CityId,Name) values (71,'Delice')
insert into Districts (CityId,Name) values (71,'Karakeçili')
insert into Districts (CityId,Name) values (71,'Keskin')
insert into Districts (CityId,Name) values (71,'Merkez')
insert into Districts (CityId,Name) values (71,'Sulakyurt')
insert into Districts (CityId,Name) values (71,'Yahþihan')

-- 72 Ýlçesi
insert into Districts (CityId,Name) values (72,'Beþiri')
insert into Districts (CityId,Name) values (72,'Gercüþ')
insert into Districts (CityId,Name) values (72,'Hasankeyf')
insert into Districts (CityId,Name) values (72,'Kozluk')
insert into Districts (CityId,Name) values (72,'Merkez')
insert into Districts (CityId,Name) values (72,'Sason')

-- 73 Ýlçesi
insert into Districts (CityId,Name) values (73,'Beytüþþebap')
insert into Districts (CityId,Name) values (73,'Cizre')
insert into Districts (CityId,Name) values (73,'Güçlükonak')
insert into Districts (CityId,Name) values (73,'Ýdil')
insert into Districts (CityId,Name) values (73,'Merkez')
insert into Districts (CityId,Name) values (73,'Silopi')
insert into Districts (CityId,Name) values (73,'Uludere')

-- 74 Ýlçesi
insert into Districts (CityId,Name) values (74,'Amasra')
insert into Districts (CityId,Name) values (74,'Kurucaþile')
insert into Districts (CityId,Name) values (74,'Merkez')
insert into Districts (CityId,Name) values (74,'Ulus')

-- 75 Ýlçesi
insert into Districts (CityId,Name) values (75,'Çýldýr')
insert into Districts (CityId,Name) values (75,'Damal')
insert into Districts (CityId,Name) values (75,'Göle')
insert into Districts (CityId,Name) values (75,'Hanak')
insert into Districts (CityId,Name) values (75,'Merkez')
insert into Districts (CityId,Name) values (75,'Posof')
--- keremozer.com
-- 76 Ýlçesi
insert into Districts (CityId,Name) values (76,'Aralýk')
insert into Districts (CityId,Name) values (76,'Karakoyunlu')
insert into Districts (CityId,Name) values (76,'Merkez')
insert into Districts (CityId,Name) values (76,'Tuzluca')

-- 77 Ýlçesi
insert into Districts (CityId,Name) values (77,'Altýnova')
insert into Districts (CityId,Name) values (77,'Armutlu')
insert into Districts (CityId,Name) values (77,'Çýnarcýk')
insert into Districts (CityId,Name) values (77,'Çiftlikköy')
insert into Districts (CityId,Name) values (77,'Merkez')
insert into Districts (CityId,Name) values (77,'Termal')

-- 78 Ýlçesi
insert into Districts (CityId,Name) values (78,'Eflani')
insert into Districts (CityId,Name) values (78,'Eskipazar')
insert into Districts (CityId,Name) values (78,'Merkez')
insert into Districts (CityId,Name) values (78,'Ovacýk')
insert into Districts (CityId,Name) values (78,'Safranbolu')
insert into Districts (CityId,Name) values (78,'Yenice')

-- 79 Ýlçesi
insert into Districts (CityId,Name) values (79,'Elbeyli')
insert into Districts (CityId,Name) values (79,'Merkez')
insert into Districts (CityId,Name) values (79,'Musabeyli')
insert into Districts (CityId,Name) values (79,'Polateli')

-- 80 Ýlçesi
insert into Districts (CityId,Name) values (80,'Bahçe')
insert into Districts (CityId,Name) values (80,'Düziçi')
insert into Districts (CityId,Name) values (80,'Hasanbeyli')
insert into Districts (CityId,Name) values (80,'Kadirli')
insert into Districts (CityId,Name) values (80,'Merkez')
insert into Districts (CityId,Name) values (80,'Sumbas')
insert into Districts (CityId,Name) values (80,'Toprakkale')

-- 81 Ýlçesi
insert into Districts (CityId,Name) values (81,'Akçakoca')
insert into Districts (CityId,Name) values (81,'Cumayeri')
insert into Districts (CityId,Name) values (81,'Çilimli')
insert into Districts (CityId,Name) values (81,'Gölyaka')
insert into Districts (CityId,Name) values (81,'Gümüþova')
insert into Districts (CityId,Name) values (81,'Kaynaþlý')
insert into Districts (CityId,Name) values (81,'Merkez')
insert into Districts (CityId,Name) values (81,'Yýðýlca')
